Make staticcheck happy
```
$ staticcheck
apiclient.go:15:2: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
apiclient.go:26:6: func printConnState is unused (U1000)
apiclient.go:34:47: state.NegotiatedProtocolIsMutual has been deprecated since Go 1.16 because it shouldn't be used: this value is always true.  (SA1019)
apiclient.go:181:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:197:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:208:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:247:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:262:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:273:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:285:10: error strings should not be capitalized (ST1005)
apiclient.go:289:10: error strings should not be capitalized (ST1005)
apiclient.go:289:10: error strings should not end with punctuation or newlines (ST1005)
apiclient.go:341:9: empty branch (SA9003)
apiclient.go:349:2: this value of err is never used (SA4006)
apiclient.go:355:9: empty branch (SA9003)
apiclient.go:397:2: this value of err is never used (SA4006)
apiclient.go:403:9: empty branch (SA9003)
apiclient.go:415:10: unnecessary use of fmt.Sprintf (S1039)
apiclient.go:433:2: this value of err is never used (SA4006)
bitmask.go:84:16: error strings should not be capitalized (ST1005)
bitmask.go:118:13: error strings should not be capitalized (ST1005)
certs.go:6:2: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
certs.go:46:2: config.BuildNameToCertificate has been deprecated since Go 1.14: NameToCertificate only allows associating a single certificate with a given name. Leave that field nil to let the library select the first compatible chain from Certificates.  (SA1019)
certs.go:67:2: config.BuildNameToCertificate has been deprecated since Go 1.14: NameToCertificate only allows associating a single certificate with a given name. Leave that field nil to let the library select the first compatible chain from Certificates.  (SA1019)
dawg_utils.go:31:6: type wellKnownDomainsTracker is unused (U1000)
dawg_utils.go:36:6: type wellKnownDomainsData is unused (U1000)
dawg_utils.go:44:6: func newWellKnownDomainsTracker is unused (U1000)
dawg_utils.go:63:37: func (*wellKnownDomainsTracker).isWellKnown is unused (U1000)
dawg_utils.go:78:37: func (*wellKnownDomainsTracker).rotateTracker is unused (U1000)
dawg_utils.go:99:2: const domainsFileName is unused (U1000)
dawg_utils.go:100:2: const dawgFileName is unused (U1000)
dawg_utils.go:103:6: func fetchFile is unused (U1000)
dawg_utils.go:145:6: func createDomainsList is unused (U1000)
dawg_utils.go:309:6: func makeDAWGWords is unused (U1000)
dns_utils.go:103:21: func (*ZoneData).xxxZoneTransferOut is unused (U1000)
dns_utils.go:240:25: error strings should not be capitalized (ST1005)
dns_utils.go:326:2: redundant return statement (S1023)
dns_utils.go:430:2: empty branch (SA9003)
dns_utils.go:458:9: assigning the result of this type assertion to a variable (switch rr := rr.(type)) could eliminate type assertions in switch cases (S1034)
	dns_utils.go:460:11: could eliminate this type assertion
	dns_utils.go:467:11: could eliminate this type assertion
	dns_utils.go:474:12: could eliminate this type assertion
dns_utils.go:490:10: assigning the result of this type assertion to a variable (switch rr := rr.(type)) could eliminate type assertions in switch cases (S1034)
	dns_utils.go:492:12: could eliminate this type assertion
	dns_utils.go:499:12: could eliminate this type assertion
	dns_utils.go:506:13: could eliminate this type assertion
mqtt_utils.go:44:15: error strings should not be capitalized (ST1005)
mqtt_utils.go:181:11: paho.NewSingleHandlerRouter is deprecated: SingleHandlerRouter has been removed because it did not meet the requirements set out in the `Router` interface documentation. This function is only included to maintain compatibility, but there are limits (this version does not ignore calls to `RegisterHandler`).  (SA1019)
mqtt_utils.go:228:15: unnecessary assignment to the blank identifier (S1005)
mqtt_utils.go:446:3: should use for range instead of for { select {} } (S1000)
mqtt_utils.go:460:3: should use for range instead of for { select {} } (S1000)
rr_set.go:89:6: func quickSort is unused (U1000)
structs.go:127:2: field apiKey is unused (U1000)
zone_utils.go:165:11: unnecessary assignment to the blank identifier (S1005)
```